apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rqi4ul0y6-go 
  janus-idp.io/tekton: rqi4ul0y6-go
  backstage.io/kubernetes-id: rqi4ul0y6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rqi4ul0y6-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  